services:
  tareas_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P4ssw0rd!
      TZ: America/Montevideo
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    networks:
      - api-tareas

  tareas_db.configurator:
    image: mcr.microsoft.com/mssql/server:2019-latest
    depends_on:
      tareas_db:
        condition: service_healthy
    environment:
      SA_PASSWORD: P4ssw0rd!
      DB_NAME: laravel
    command: |
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S tareas_db -U sa -P $${SA_PASSWORD} -C -Q "IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = \"$${DB_NAME}\") BEGIN CREATE DATABASE $${DB_NAME} END " || exit
      '
    networks:
      - api-tareas

  tareas_php-fpm:
    build: docker/php-fpm
    depends_on:
        tareas_db.configurator:
            condition: service_completed_successfully
    networks:
      - api-oauth_intranet
      - api-tareas
    volumes:
      - ./:/var/www/html

  tareas_apache:
    build:
      context: docker/apache
      args:
          PHP_FPM_URL: "tareas_php-fpm"
    ports:
      - "8000:80"
    networks:
      - api-tareas
    volumes:
      - ./public:/var/www/html/public

networks:
  api-tareas:
    driver: bridge
  api-oauth_intranet:
    external: true
