services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: P4ssw0rd!
      TZ: America/Montevideo
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $${SA_PASSWORD} -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s

  db.configurator:
    image: mcr.microsoft.com/mssql/server:2019-latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      SA_PASSWORD: P4ssw0rd!
      DB_NAME: laravel
    command: |
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S db -U sa -P $${SA_PASSWORD} -C -Q "IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = \"$${DB_NAME}\") BEGIN CREATE DATABASE $${DB_NAME} END " || exit
      '

  php-fpm:
    build: docker/php-fpm
    depends_on:
        db.configurator:
            condition: service_completed_successfully
    volumes:
      - ./:/var/www/html

  apache:
    build: docker/apache
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/html/public
