apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: api-tareas-obligatorio-tecredsw
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: api-tareas-obligatorio-tecredsw
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  namespace: api-tareas-obligatorio-tecredsw
spec:
  selector:
    app: php-fpm
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: api-tareas-obligatorio-tecredsw
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
